---
- name: configure APT sources
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        # We use `ansible_lsb.id` instead of `ansible_distribution`, because
        # the value of `ansible_distribution` on Raspbian is `Debian`.
        - '{{ ansible_lsb.id }}.yml'
        - default.yml

- meta: flush_handlers
